---
- name: Login into dockerhub and push an image
  hosts: 172.31.18.115
  tasks:
   - name: Login into dockerhub
     docker_login:
      username: sai
      password: intelliqit
      email: intelliqit@gmail.com
   - name: Push the docker image
     docker_image:
      name: intelliqit/centos_3_april 
      push: yes 

